// <auto-generated>

namespace VanguardModelPFScrewdriver
{
    using System.Reflection;

    internal class Constants
    {
        internal class Caption
        {
            /// <summary>
            /// Dictionary to get caption number from caption name
            /// </summary>
            private static Dictionary<string, int> _captionMap = typeof(Caption)
                .GetFields(BindingFlags.Public | BindingFlags.Static)
                .Where(x => x.IsLiteral && x.FieldType == typeof(int))
                .ToDictionary(x => x.Name, x => (int)x.GetRawConstantValue());

            /// <summary>
            /// Gets caption number from caption name
            /// </summary>
            /// <param name="name">Caption name</param>
            /// <returns>Caption number, or null for unknown name</returns>
            public static int? NameToNumber(
                string name
            )
            {
                return _captionMap.TryGetValue(name, out var number) ? number : null;
            }

            public const int ExtensionName = 0;
            public const int OK = 10;
            public const int Cancel = 11;
            public const int Enabled = 20;
            public const int Name = 21;
            public const int Value = 22;
            public const int Torque = 23;
            public const int FileCategory = 200;
            public const int FileTypeName = 201;
            public const int AddLibraryMenuItem = 210;
            public const int ImportLibraryFailed = 220;
            public const int AddLibraryCompleted = 221;
            public const int AddLibraryFailed = 222;
            public const int WindowTitle = 400;
            public const int QueryClose = 410;
            public const int CannotClose = 411;
            public const int CannotSave = 412;
            public const int ChangeProgramWarning = 413;
            public const int FetchFromController = 450;
            public const int SelectUSBDrive = 451;
            public const int ResultLog = 500;
            public const int ErrorLog_old = 501;
            public const int ErrorLog = 502;
            public const int LineNo = 509;
            public const int DateTime = 510;
            public const int ProgramNo = 511;
            public const int MaxTorque = 512;
            public const int ElapsedTime = 513;
            public const int Result = 514;
            public const int ErrorDetail = 515;
            public const int DrawWave = 516;
            public const int CTConts = 520;
            public const int Description = 521;
            public const int Operation = 522;
            public const int TorqueUpperLimitLabel = 600;
            public const int NumTurnsUpperLimitLabel = 601;
            public const int ScaleAuto = 602;
            public const int ScaleFixed = 603;
            public const int NetworkGroup = 1100;
            public const int ConnectFromPC = 1101;
            public const int DisconnectFromPC = 1102;
            public const int ControllerSettings = 1103;
            public const int SysInfoGroup = 1200;
            public const int ToolTypeLabel = 1201;
            public const int ChangeToolType = 1202;
            public const int ProgramGroup = 1300;
            public const int AllPrograms = 1310;
            public const int SelectedProgram = 1311;
            public const int DownloadProgram = 1320;
            public const int UploadProgram = 1321;
            public const int ImportProgram = 1322;
            public const int ExportProgram = 1323;
            public const int Tightening = 1330;
            public const int Loosening = 1331;
            public const int Rotation = 1332;
            public const int StartOperation = 1340;
            public const int StopOperation = 1341;
            public const int OperationState = 1350;
            public const int VacuumControl = 1400;
            public const int VacuumOn = 1410;
            public const int VacuumBreakOn = 1411;
            public const int VacuumSuctionState = 1412;
            public const int DownloadOverwriteWarning = 1500;
            public const int ImportOverwriteWarning = 1501;
            public const int DiscardChangesWarning = 1502;
            public const int PreferencesDialog = 2000;
            public const int TorqueUnitLabel = 2001;
            public const int TorqueUnitMNM = 2002;
            public const int TorqueUnitKGFCM = 2003;
            public const int LogStorageLabel = 2010;
            public const int LogStoragePC = 2011;
            public const int LogStorageUSB = 2012;
            public const int LogStorageFlash = 2013;
            public const int FolderLabel = 2014;
            public const int SelectFolder = 2015;
            public const int MaxNumFilesOnPassLabel = 2016;
            public const int MaxNumFilesOnFailLabel = 2017;
            public const int LoggingNotice1 = 2020;
            public const int LoggingNotice2 = 2021;
            public const int PCStorageNotice = 2022;
            public const int USBStorageNotice1 = 2023;
            public const int USBStorageNotice2 = 2024;
            public const int FlashStorageNotice1 = 2025;
            public const int FlashStorageNotice2 = 2026;
            public const int BadPathError = 2030;
            public const int ConnectFromPCDialog = 2100;
            public const int IPAddressLabel = 2101;
            public const int ConnectTimeoutLabel = 2102;
            public const int Milisecond = 2103;
            public const int PanicGroup = 2110;
            public const int PanicProc1 = 2111;
            public const int PanicProc2 = 2112;
            public const int PanicProc3 = 2113;
            public const int PanicProc4 = 2114;
            public const int PanicProc4Sub1 = 2115;
            public const int PanicProc4Sub2 = 2116;
            public const int PanicProc4Sub3 = 2117;
            public const int PanicProc5 = 2118;
            public const int PanicProc6 = 2119;
            public const int DefaultSettings = 2130;
            public const int Connect = 2131;
            public const int CannotConnectError = 2140;
            public const int DifferentToolTypeWarning = 1141;
            public const int ControllerSettingsDialog = 2200;
            public const int CTContsSettingsGroup = 2210;
            public const int SubnetMaskLabel = 2211;
            public const int GatewayLabel = 2212;
            public const int SavedRadio = 2213;
            public const int DownloadedRadio = 2214;
            public const int RobotControllerSettingsGroup = 2220;
            public const int TCPPortLabel = 2221;
            public const int TCPPortIPAddressLabel = 2222;
            public const int ControllerIPAddressLabel = 2223;
            public const int NetworkNotice1 = 2230;
            public const int NetworkNotice2 = 2231;
            public const int SetDownloadedValues = 2232;
            public const int SetFileValues = 2233;
            public const int CannotUploadError = 2340;
            public const int RobotControllerSettingsError = 2341;
            public const int SysInfoDialog = 2300;
            public const int CTContsInfoGroup = 2301;
            public const int SerialNoLabel = 2302;
            public const int TotalNumTighteningLabel = 2303;
            public const int TMCVersionLabel = 2304;
            public const int SDCVersionLabel = 2305;
            public const int MACAddressLabel = 2306;
            public const int DriverInfoGroup = 2310;
            public const int ChangeToolTypeDialog = 2400;
            public const int VacuumSettingsDialog = 2500;
            public const int IOLabelLabel = 2501;
            public const int VacuumOnLabel = 2502;
            public const int VacuumBreakOnLabel = 2503;
            public const int SuctionStateLabel = 2504;
            public const int ProgramEditorDialog = 2600;
            public const int ProgramNameLabel = 2601;
            public const int ProgramNameHint = 2602;
            public const int InputHintLabel = 2603;
            public const int DirectionLabel = 2610;
            public const int TargetTorqueLabel = 2611;
            public const int StepLabel = 2612;
            public const int NumTurns = 2613;
            public const int Speed = 2614;
            public const int SamplingAngleLabel = 2615;
            public const int TorqueAdjustRateLabel = 2620;
            public const int WindowLabel = 2621;
            public const int Configure = 2622;
            public const int TighteningSpecialParameters = 2630;
            public const int TighteningModeLabel = 2631;
            public const int NormalMode = 2632;
            public const int TappingMode = 2633;
            public const int FastMode = 2634;
            public const int StartDetectionAmount = 2635;
            public const int InitialTappingTorque = 2636;
            public const int TorqueUpDetectionTime = 2637;
            public const int PermissibleTurnsBelow = 2638;
            public const int PermissibleTurnsAbove = 2639;
            public const int FurtherTighteningAngle = 2640;
            public const int FurtherTighteningAngleForProtruding = 2641;
            public const int TorqueThresholdToChangeSpeed = 2642;
            public const int SpeedAfterChanged = 2643;
            public const int UploadThisProgram = 2650;
            public const int WindowSettingsDialog = 2700;
            public const int WindowNumber = 2710;
            public const int StartTurn = 2711;
            public const int EndTurn = 2712;
            public const int TorqueAtStart = 2713;
            public const int TorqueAtEnd = 2714;
            public const int TorqueWidth = 2715;
            public const int LineWidth = 2716;
            public const int LinePattern = 2717;
            public const int LineColor = 2718;
            public const int DOError0 = 3000;
            public const int DOError1 = 3001;
            public const int DOError2 = 3002;
            public const int DOError3 = 3003;
            public const int DOError4 = 3004;
            public const int DOError5 = 3005;
            public const int DOError6 = 3006;
            public const int DOError7 = 3007;
            public const int DOError8 = 3008;
            public const int DOError9 = 3009;
            public const int DOError10 = 3010;
            public const int DOError11 = 3011;
            public const int DOError12 = 3012;
            public const int DOError13 = 3013;
            public const int DOError14 = 3014;
            public const int DOError15 = 3015;
            public const int ErrorOp0 = 3020;
            public const int ErrorOp1 = 3021;
            public const int ErrorOp2 = 3022;
            public const int ErrorOp3 = 3023;
            public const int ErrorOp4 = 3024;
            public const int ErrorOp5 = 3025;
            public const int ErrorOp6 = 3026;
            public const int ErrorOp7 = 3027;
            public const int ErrorOp8 = 3028;
            public const int ErrorOp9 = 3029;
            public const int ErrorOp10 = 3030;
            public const int ErrorOp11 = 3031;
            public const int ErrorOp12 = 3032;
            public const int ErrorOp13 = 3033;
            public const int ProgramDownloadError = 3100;
            public const int ProgramUploadError = 3101;
            public const int NetConfDownloadError = 3102;
            public const int NetConfUploadError = 3103;
            public const int SysInfoDownloadError = 3104;
            public const int ImportProgramFailed = 3105;
            public const int ExportProgramFailed = 3106;
            public const int CreateDefFileFailed = 3107;
            public const int LoadDefFileFailed = 3108;
            public const int SaveDefFileFailed = 3109;
            public const int LogReadingError = 3110;
            public const int LogAppendingError = 3111;
            public const int SaveWaveDataFailed = 3112;
            public const int LoadWaveDataFailed = 3113;
            public const int IOWritingError = 3114;
            public const int CannotCreateWatcher = 3115;
            public const int SaveControllerSettingsFailed = 3116;
            public const int DownloadingPrograms = 3150;
            public const int UploadingPrograms = 3151;
            public const int PEProgramFilter = 3152;
            public const int FetchingTorqueData = 3153;
            public const int WaitingConnection = 3154;
            public const int NoProgramSteps = 3155;
            public const int ErrorDetail0 = 3200;
            public const int ErrorDetail1 = 3201;
            public const int ErrorDetail2 = 3202;
            public const int ErrorDetail3 = 3203;
            public const int ErrorDetail4 = 3204;
            public const int ErrorDetail5 = 3205;
            public const int ErrorDetail6 = 3206;
            public const int ErrorDetail7 = 3207;
            public const int ErrorDetail8 = 3208;
            public const int ErrorDetail9 = 3209;
            public const int ErrorDetail10 = 3210;
            public const int ErrorDetail11 = 3211;
            public const int ErrorDetail12 = 3212;
            public const int ErrorDetail13 = 3213;
            public const int ErrorDetail14 = 3214;
            public const int ErrorDetail15 = 3215;
            public const int ErrorDetail16 = 3216;
            public const int ErrorDetail17 = 3217;
            public const int ErrorDetail20 = 3220;
            public const int ErrorDetail21 = 3221;
            public const int OperationCompleted = 3300;
        }
    }
}
