// <auto-generated>

namespace VanguardModelPFScrewdriver
{
    public static partial class ExtensionIdentity
    {
        public const string Name = "VanguardModelPFScrewdriver";
        public const string Guid = "728ed9c2-e8ca-4935-aeeb-2afba2bf2626";
        public const string Id = $"{Name}_{Guid}";
    }
}
