'||
'|| JA: 上下限値
'|| EN: Constants for Min - Max
'||
#define COM_MIN 1		' JA: COMポート番号下限 EN: Minimum value of COM Port No.
#define COM_MAX 8		' JA: COMポート番号上限 EN: Maxim value of COM Port No.
#define COM_PC_MIN 1001 ' JA: COMポート(PC)番号下限 EN: Minimum value of COM Port No. (PC)
#define COM_PC_MAX 1008 ' JA: COMポート(PC)番号下限 EN: Maxim value of COM Port No. (PC)
#define RECIPE_MIN 1	' JA: レシピ番号下限 EN: Minimum value of Recipe No.
#define RECIPE_MAX 16	' JA: レシピ番号上限 EN: Maxim value of Recipe No.
#define MODE_POS 0		' JA: 把持動作モード EN: Gripping mode
#define MODE_GRIP 2		' JA: 位置決め動作モード EN: Positioning mode
#define POS_MIN 0.0		' JA: 位置下限[mm] EN: Minimum value of Position
#define POS_MAX 50.0	' JA: 位置上限[mm] EN: Maxim value of Position
#define SPD_POS_MIN 5.0		' JA: 位置決め時の速度下限[mm/sec] EN: Minimum value of speed when positioning
#define SPD_POS_MAX 100.0	' JA: 位置決め時の速度上限[mm/sec] EN: Maxim value of speed when positioning
#define FORCE_MIN 60.0		' JA: 把持力の最小値[N] EN: Minimum value of gripping
#define FORCE_MAX 140.0		' JA: 把持力の最大値[N] EN: Maxim value of gripping

#define SERVO_OFF 0		' JA: サーボOFF EN: Servo OFF
#define SERVO_ON 1		' JA: サーボON  EN: Servo ON

