// <auto-generated>

namespace IntegratedJogPanel
{
    using System.Reflection;

    internal class Constants
    {
        internal class Caption
        {
            /// <summary>
            /// Dictionary to get caption number from caption name
            /// </summary>
            private static Dictionary<string, int> _captionMap = typeof(Caption)
                .GetFields(BindingFlags.Public | BindingFlags.Static)
                .Where(x => x.IsLiteral && x.FieldType == typeof(int))
                .ToDictionary(x => x.Name, x => (int)x.GetRawConstantValue());

            /// <summary>
            /// Gets caption number from caption name
            /// </summary>
            /// <param name="name">Caption name</param>
            /// <returns>Caption number, or null for unknown name</returns>
            public static int? NameToNumber(
                string name
            )
            {
                return _captionMap.TryGetValue(name, out var number) ? number : null;
            }

            public const int ExtensionName = 0;
            public const int MainMenu = 1;
            public const int PECategory = 100;
            public const int PEItem = 110;
            public const int PEItemMenu = 120;
            public const int FileCategory = 200;
            public const int FileTypeName = 201;
            public const int EditorHeader = 300;
            public const int WindowTitle = 400;
            public const int WindowHeader = 401;
            public const int Common_OK = 501;
            public const int Common_Cancel = 502;
            public const int Common_Reset = 503;
            public const int Gen_ToJogOnly = 10001;
            public const int Gen_WholeMode = 10002;
            public const int JogArea_Title = 11000;
            public const int JogArea_JogLaytout = 11001;
            public const int JogArea_Edit = 11002;
            public const int JogArea_UpdatePoint = 11003;
            public const int JogArea_InsertBefore = 11004;
            public const int JogArea_InsertAfter = 11005;
            public const int JogArea_AddPoint = 11006;
            public const int JogArea_ControllerConnect = 11007;
            public const int JogLayoutPanel_HiddenItems = 11101;
            public const int JogLayoutPanel_Visibletems = 11102;
            public const int JogLayoutPanel_Up = 11103;
            public const int JogLayoutPanel_Down = 11104;
            public const int IOBitSelectWin_Title = 11200;
            public const int JogDistanceWin_Title = 11300;
            public const int JogDistanceWin_SpinInteger = 11301;
            public const int JogDistanceWin_AccordMMDistance = 11302;
            public const int JogDistanceWin_AccordDegDistance = 11303;
            public const int PointsArea_Title = 12000;
            public const int PointsArea_EditUp = 12001;
            public const int PointsArea_EditUp_Tip = 12002;
            public const int PointsArea_EditDown = 12003;
            public const int PointsArea_EditDown_Tip = 12004;
            public const int PointsArea_EditRemove = 12005;
            public const int PointsArea_EditRemove_Tip = 12006;
            public const int PointsArea_EditRemoveAll = 12007;
            public const int PointsArea_EditRemoveAll_Tip = 12008;
            public const int PointsArea_MotionToSelect = 12009;
            public const int PointsArea_MotionToSelect_Tip = 12010;
            public const int PointsArea_MotionHeadToSelect = 12011;
            public const int PointsArea_MotionHeadToSelect_Tip = 12012;
            public const int PointsArea_MotionHeadToTail = 12013;
            public const int PointsArea_MotionHeadToTail_Tip = 12014;
            public const int PointsArea_PointsFromClipboard = 12015;
            public const int PointsArea_PointsFromClipboard_Tip = 12016;
            public const int PointsArea_PointsToClipboard = 12017;
            public const int PointsArea_PointsToClipboard_Tip = 12018;
            public const int PointsArea_LoadPoints = 12019;
            public const int PointsArea_LoadPoints_Tip = 12020;
            public const int PointsArea_SavePoints = 12021;
            public const int PointsArea_SavePoints_Tip = 12022;
            public const int PointsArea_Editable = 12023;
            public const int PointsArea_Stop = 12024;
            public const int PointsArea_Stop_Tip = 12025;
            public const int PointsArea_PtsLoadErrorNotSequential = 12026;
            public const int PointsArea_PtsLoadErrorLocal = 12027;
            public const int PointsArea_PtsLoadConfirmOverwrite = 12028;
            public const int PointsArea_PtsSaveError = 12029;
            public const int LoadPtsWin_Title = 12100;
            public const int ViewArea_Title = 13000;
            public const int ViewArea_GuideNormalMode = 13001;
            public const int ViewArea_GuideAdjustMode = 13002;
            public const int ViewArea_RobotInformation = 13003;
            public const int ViewArea_ViewDirection = 13004;
            public const int ViewArea_ToolJogButtonLayout = 13005;
            public const int ViewArea_ShowPoints = 13006;
            public const int ViewArea_ShowLocus = 13007;
            public const int ViewArea_ShowPtAdv = 13008;
            public const int ViewArea_ShowPtLabel = 13009;
            public const int VewiArea_ShowPtTool = 13010;
            public const int ViewArea_AdjustMode = 13011;
            public const int VewiArea_AdjustModeWarn = 13012;
            public const int ViewArea_AdujustModeWan2 = 13013;
            public const int ViewArea_AdujustModeChange = 13014;
            public const int ViewArea_AdujustModeAvailabelDistanceMsg = 13015;
        }
    }
}
