// <auto-generated>

namespace IntegratedJogPanel
{
    public static partial class ExtensionIdentity
    {
        public const string Name = "IntegratedJogPanel";
        public const string Guid = "841a13a3-4730-4591-bb8a-47c31dc2f8ee";
        public const string Id = $"{Name}_{Guid}";
    }
}
