// <auto-generated>

namespace SMCElectricGripper
{
    using System.Reflection;

    internal class Constants
    {
        internal class Caption
        {
            /// <summary>
            /// Dictionary to get caption number from caption name
            /// </summary>
            private static Dictionary<string, int> _captionMap = typeof(Caption)
                .GetFields(BindingFlags.Public | BindingFlags.Static)
                .Where(x => x.IsLiteral && x.FieldType == typeof(int))
                .ToDictionary(x => x.Name, x => (int)x.GetRawConstantValue());

            /// <summary>
            /// Gets caption number from caption name
            /// </summary>
            /// <param name="name">Caption name</param>
            /// <returns>Caption number, or null for unknown name</returns>
            public static int? NameToNumber(
                string name
            )
            {
                return _captionMap.TryGetValue(name, out var number) ? number : null;
            }

            public const int ExtensionName = 0;
            public const int ParentMainMenu = 1;
            public const int SettingsMenu = 2;
            public const int ImportLibraryMenu = 3;
            public const int WindowTitle = 4;
            public const int UnsupportedRcPlusVersionMessage = 100;
            public const int LibraryImportCompletedMessage = 101;
            public const int LibraryImportFailedMessage = 102;
            public const int LibraryProjectNotOpenMessage = 103;
            public const int ControllerConnectionFailedMessage = 104;
            public const int GripperConnectionFailedMessage = 105;
            public const int MotionSettingsBackupFailedMessage = 106;
            public const int MotionSettingsLoadFailedMessage = 107;
            public const int BackgroundTaskDisabledMessage = 108;
            public const int LibraryProjectAddFailedMessage = 109;
            public const int ConnectionSettingsTitle = 200;
            public const int ConnectionPortLabel = 201;
            public const int ConnectionButton = 202;
            public const int DisconnectionButton = 203;
            public const int MotionSettingsTitle = 300;
            public const int RecipeNumberLabel = 301;
            public const int OperationModeLabel = 302;
            public const int PositioningRadioButton = 303;
            public const int GrippingRadioButton = 304;
            public const int PositionLabel = 305;
            public const int SpeedLabel = 306;
            public const int ForceLabel = 307;
            public const int BackupSettingsButton = 308;
            public const int RestoreSettingsButton = 309;
            public const int BackupSettingsLabel = 310;
            public const int RestoreSettingsLabel = 311;
            public const int RunTitle = 400;
            public const int ServoOnButton = 401;
            public const int ServoOffButton = 402;
            public const int ResetButton = 403;
            public const int ExecuteButton = 404;
            public const int AbortButton = 405;
            public const int JogLabel = 406;
            public const int OpenButton = 407;
            public const int CloseButton = 408;
            public const int StatusLabel = 409;
            public const int CurrentPositionLabel = 410;
            public const int RefreshStatusButton = 411;
            public const int ServoLabel = 412;
        }
    }
}
