// <auto-generated>

namespace SMCElectricGripper
{
    public static partial class ExtensionIdentity
    {
        public const string Name = "SMCElectricGripper";
        public const string Guid = "e7c7851d-4638-4576-9113-4a73a58c4bfc";
        public const string Id = $"{Name}_{Guid}";
    }
}
