// <auto-generated>

namespace WebCamRecorder
{
    using System.Reflection;

    internal class Constants
    {
        internal class Caption
        {
            /// <summary>
            /// Dictionary to get caption number from caption name
            /// </summary>
            private static Dictionary<string, int> _captionMap = typeof(Caption)
                .GetFields(BindingFlags.Public | BindingFlags.Static)
                .Where(x => x.IsLiteral && x.FieldType == typeof(int))
                .ToDictionary(x => x.Name, x => (int)x.GetRawConstantValue());

            /// <summary>
            /// Gets caption number from caption name
            /// </summary>
            /// <param name="name">Caption name</param>
            /// <returns>Caption number, or null for unknown name</returns>
            public static int? NameToNumber(
                string name
            )
            {
                return _captionMap.TryGetValue(name, out var number) ? number : null;
            }

            public const int ExtensionName = 0;
            public const int MainMenu = 1;
            public const int WindowTitle = 400;
            public const int CaptionCamera = 401;
            public const int LabelStart = 402;
            public const int LabelStop = 403;
        }
    }
}
