// <auto-generated>

namespace SpelAnalysisTool
{
    using System.Reflection;

    internal class Constants
    {
        internal class Caption
        {
            /// <summary>
            /// Dictionary to get caption number from caption name
            /// </summary>
            private static Dictionary<string, int> _captionMap = typeof(Caption)
                .GetFields(BindingFlags.Public | BindingFlags.Static)
                .Where(x => x.IsLiteral && x.FieldType == typeof(int))
                .ToDictionary(x => x.Name, x => (int)x.GetRawConstantValue());

            /// <summary>
            /// Gets caption number from caption name
            /// </summary>
            /// <param name="name">Caption name</param>
            /// <returns>Caption number, or null for unknown name</returns>
            public static int? NameToNumber(
                string name
            )
            {
                return _captionMap.TryGetValue(name, out var number) ? number : null;
            }

            public const int ExtensionName = 1;
            public const int Common_OK = 100;
            public const int Common_Cancel = 102;
            public const int Hdr_StartFunction = 1001;
            public const int Hdr_LoadCSV = 1002;
            public const int Hdr_AddSpelLogger = 1003;
            public const int Hdr_Layout = 1004;
            public const int ChkParams_Title = 1100;
            public const int ChkParams_Apply = 1101;
            public const int AdjParams_Title = 1200;
            public const int AdjParams_WriteToInc = 1201;
            public const int AdjParams_Remove = 1202;
            public const int View_Title = 1300;
            public const int View_Live = 1301;
            public const int View_Reenact = 1302;
            public const int Motion_GraphNum = 1601;
            public const int Layout_HiddenItems = 1701;
            public const int Layout_VisibleItems = 1702;
            public const int Layout_Reset = 1703;
            public const int StartFunction_Title = 2000;
            public const int StartFunction_StartFunction = 2001;
            public const int StartFunction_Function = 2003;
            public const int StartFunction_ReadLogInRuntime = 2004;
            public const int AddSpelLogger_Title = 3000;
            public const int AddSpelLogger_SpelLoggerType = 3001;
            public const int AddSpelLogger_File = 3002;
            public const int AddSpelLogger_Library = 3003;
            public const int AddSpelLogger_AddSample = 3004;
            public const int Msg_LibraryImportFailed = 10001;
            public const int Msg_LibraryProjectAddFailed = 10002;
        }
    }
}
