// <auto-generated>

namespace SpelAnalysisTool
{
    public static partial class ExtensionIdentity
    {
        public const string Name = "SpelAnalysisTool";
        public const string Guid = "0a8c4e66-1e0b-420c-87d8-482129214e8d";
        public const string Id = $"{Name}_{Guid}";
    }
}
